[package]
name = "mediancut-wasm"
description = "Median Cut algorithm implemented in Rust and compiled to WebAssembly"
repository = "git+https://github.com/t4y3/mediancut.git"
license = "MIT"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2.91"
serde = { version = "1.0.197", features = ["derive"] }
serde_json = "1.0.114"
